title: Bulma Theme Manager Demo
description: Minimal Jekyll site showcasing Bulma components with theme switch
baseurl: ''
url: 'https://lgtm-hq.github.io'

# Site metadata used by jekyll-seo-tag
logo: '/assets/img/bulma-logo.png'
lang: 'en'

theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /:collection/:name/
  es:
    output: true
    permalink: /es/:name/

defaults:
  - scope:
      path: playwright-report
    values:
      sitemap: false
  - scope:
      path: coverage
    values:
      sitemap: false

exclude:
  - node_modules
  - vendor
  - .bundle
  - package-lock.json
  - Gemfile.lock

include:
  - dist
  - assets
  - coverage
  - playwright-report
  - lighthouse-reports
